# Generated by Django 5.2.7 on 2025-10-26 23:08

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacaoestoque',
            name='valor_total',
            field=models.GeneratedField(db_persist=False, expression=django.db.models.expressions.CombinedExpression(models.F('quantidade'), '*', models.F('preco_unidade')), output_field=models.DecimalField(decimal_places=4, max_digits=10)),
        ),
        migrations.AlterField(
            model_name='solicitacaoevento',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item'),
        ),
        migrations.AlterField(
            model_name='transacaoestoque',
            name='tipo',
            field=models.CharField(choices=[('compra', 'Compra'), ('alocacao', 'Alocação para Evento'), ('retorno', 'Retorno de Evento'), ('remocao', 'Remoção Manual'), ('adicao', 'Adição Manual'), ('patrocinio', 'Patrocínio'), ('conssumo', 'Consumo Interno')], db_index=True, max_length=20),
        ),
    ]
