# Generated by Django 5.2.7 on 2025-10-28 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacaoestoque',
            name='evento',
            field=models.ForeignKey(blank=True, limit_choices_to={'status': 'andamento'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes', to='core.evento'),
        ),
    ]
